### ISSUE TITLE
How to deal with mesh data

### ISSUE THREAD

**Issue by daidaista** [deepsphere/deepsphere-cosmo-tf1#34]
Hi, thanks for developing such a great tool. I’m trying to apply healpy to my spherical mesh data for the purpose of interpolation, my mesh data contains face and vertex information and feature information at each vertex. I’m wondering how can I interpolate my mesh data so I can use DeepSphere? Thanks!

**Comment by nperraud** [comment]
As you know, the current implementation does not take faces informations.  A bad solution would be to use a function to send the faces information onto the adjacent vertices. A good solution requires more work/research and would be to use a different type of GNN that uses faces information as well.

**Comment by mdeff** [comment]
Thanks for your kind words @daidaista. In theory, because the sphere is a 2D manifold, vertex-valued and face-valued functions are equivalent (while edge-valued functions are different). What are your vertex and face features? Couldn't you sample them at the same positions? As you both suggested, interpolation is otherwise a solution (which is usually not bad in practice). Another solution would be to use a different graph for your vertex and face data (the graph supporting the face data would have one vertex per face of the original graph).
